GlobalProtestCalendar/Models/Protest/NewProtestModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using GlobalProtestCalendar.Business;
using GlobalProtestCalendar.Business.Services;
using Microsoft.AspNetCore.Http;

namespace GlobalProtestCalendar.Models.Protest
{
    public class NewProtestModel : IValidatableObject
    {
        public NewProtestModel()
        {
        }

        public NewProtestModel(Data.Models.Protest protest)
        {
            Id = protest.Id;
            Country = protest.Country;
            Duration = protest.Duration;
            Location = protest.Location;
            ExpectedOutcome = protest.ExpectedOutcome;
            LocationDetails = protest.LocationDetails;
            ProtestDescription = protest.ProtestDescription;
            ProtestName = protest.ProtestName;
            StartDate = protest.StartDate;
            CoverImageUrl = protest.CoverImagePath;

            if (protest.Motivation.HasFlag(Protest.Motivation.Political))
            {
                Motivation = Motivation.Concat(new[] {Protest.Motivation.Political}).ToArray();
            }

            if (protest.Motivation.HasFlag(Protest.Motivation.Corruption))
            {
                Motivation = Motivation.Concat(new[] {Protest.Motivation.Corruption}).ToArray();
            }

            if (protest.Motivation.HasFlag(Protest.Motivation.Economic))
            {
                Motivation = Motivation.Concat(new[] {Protest.Motivation.Economic}).ToArray();
            }
        }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "ProtestName")]
        [StringLength(Constants.MaxProtestNameLength)]
        public string ProtestName { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "ProtestDescription")]
        [StringLength(Constants.MaxProtestDescriptionLength)]
        public string ProtestDescription { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Country")]
        [StringLength(Constants.MaxCountryNameLength)]
        public string Country { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Location")]
        [StringLength(Constants.MaxLocationNameLength)]
        public string Location { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "LocationDetails")]
        [StringLength(Constants.MaxLocationDetailsLength)]
        public string LocationDetails { get; set; }

        [Display(Name = "StartDate")] public DateTime StartDate { get; set; } = DateTime.UtcNow;

        [Required(ErrorMessage = "Required")]
        [StringLength(Constants.MaxDurationNameLength)]
        public string Duration { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "ExpectedOutcome")]
        [StringLength(Constants.MaxExpectedOutcomeLength)]
        public string ExpectedOutcome { get; set; }

        [Display(Name = "Motivation")]
        [Required(ErrorMessage = "NoMotivation")]
        public Motivation[] Motivation { get; set; } = {Protest.Motivation.Political};

        [Display(Name = "CoverImage")] public IFormFile CoverImage { get; set; }

        public string CoverImageUrl { get; set; } = "/img/new-protest.jpeg";

        public Guid Id { get; set; }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (Motivation.Any(m => m == Protest.Motivation.None))
            {
                yield return new ValidationResult("Required", new[] {"Motivation"});
            }

            if (LocalizedCountryList.CountryList.First().Value.All(kvp => kvp.Key != Country))
            {
                yield return new ValidationResult("Required", new[] {nameof(Country)});
            }
        }
    }

    [Flags]
    public enum Motivation
    {
        None = 0,
        Political = 1,
        Economic = 2,
        Corruption = 4
    }
}

GlobalProtestCalendar/Models/Protest/ProtestDetailsViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using GlobalProtestCalendar.Data.Models;

namespace GlobalProtestCalendar.Models.Protest
{
    public class ProtestDetailsViewModel : NewProtestModel
    {
        public bool IsOwner { get; }

        public bool IsAttending { get; }

        public IList<ProtestComment> Comments { get; }

        public ProtestDetailsViewModel(Data.Models.Protest protest, string link, in bool isAttending, IList<ProtestComment> comments, int confirmedAttendees) : base(protest)
        {
            IsOwner = protest.User == link;
            IsAttending = isAttending;
            Comments = comments;
            ConfirmedAttendees = confirmedAttendees;
        }

        [Display(Name = "ConfirmedAttendees")]
        public int ConfirmedAttendees { get; set; }
    }
}

GlobalProtestCalendar/Models/Protest/ProtestListItem.cs
using System;

namespace GlobalProtestCalendar.Models.Protest
{
    public class ProtestListItem
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Duration { get; set; }
        public Motivation Motivation { get; set; }
        public string ExpectedOutcome { get; set; }
        public string StartDate { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }
    }
}

GlobalProtestCalendar/Controllers/CommentsController.cs
using System.Threading.Tasks;
using GlobalProtestCalendar.Business.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace GlobalProtestCalendar.Controllers
{
    public class CommentsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ProtestCreationService _service;
        private readonly CommonLocalizationService _localizationService;
        private readonly ProtestQueryService _protestQueryService;

        public CommentsController(ILogger<HomeController> logger, ProtestCreationService service, CommonLocalizationService localizationService, ProtestQueryService protestQueryService)
        {
            _logger = logger;
            _service = service;
            _localizationService = localizationService;
            _protestQueryService = protestQueryService;
        }

        [HttpPost]
        public async Task<IActionResult> Index()
        {
            // INCREASE ATTENDING COUNT WHEN USER CLICKS ATTENDING
            return Ok();
        }

    }
}

GlobalProtestCalendar/Controllers/ProtestsController.cs
using System;
using System.Threading.Tasks;
using GlobalProtestCalendar.Business;
using GlobalProtestCalendar.Business.Services;
using GlobalProtestCalendar.Models.Protest;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace GlobalProtestCalendar.Controllers
{
    public class ProtestsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ProtestCreationService _service;
        private readonly CommonLocalizationService _localizationService;
        private readonly ProtestQueryService _protestQueryService;
        private readonly ProtestAttendanceService _protestAttendanceService;

        public ProtestsController(
            ILogger<HomeController> logger,
            ProtestCreationService service,
            CommonLocalizationService localizationService,
            ProtestQueryService protestQueryService,
            ProtestAttendanceService protestAttendanceService)
        {
            _logger = logger;
            _service = service;
            _localizationService = localizationService;
            _protestQueryService = protestQueryService;
            _protestAttendanceService = protestAttendanceService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var link = HttpContext.Session.GetString(Constants.UserIdHashed);

            var protests = await _protestQueryService.GetProtests(link);

            return View(protests);
        }

        [HttpGet("/protests/{protestSlugUrl}")]
        public async Task<IActionResult> Index(string protestSlugUrl)
        {
            if (!string.IsNullOrWhiteSpace(protestSlugUrl))
            {
                var i = protestSlugUrl.IndexOf(':');

                if (i > -1 && Guid.TryParse(protestSlugUrl.Substring(i + 1), out var id))
                {
                    var link = HttpContext.Session.GetString(Constants.UserIdHashed);

                    var (protest, isAttending, comments, attendees) = await _protestQueryService.GetProtestDetails(id, link);

                    if (protest != null)
                    {
                        return View("Details", new ProtestDetailsViewModel(protest, link, isAttending, comments, attendees));
                    }
                }
            }

            return NotFound();
        }

        [Authorize]
        [HttpGet]
        public IActionResult New()
        {
            return View(new NewProtestModel());
        }

        [Authorize]
        [HttpGet("/protest/edit/{id}")]
        public async Task<IActionResult> Edit([FromRoute] Guid id)
        {
            var hashedUserId = HttpContext.Session.GetString(Constants.UserIdHashed);

            var protest = await _protestQueryService.GetProtest(id, hashedUserId);

            if (protest == null)
            {
                return NotFound();
            }

            return View("Edit", new NewProtestModel(protest));
        }

        [Authorize]
        [HttpPost("/protest/edit/{id}")]
        public async Task<IActionResult> Edit(NewProtestModel model)
        {
            var hashedUserId = HttpContext.Session.GetString(Constants.UserIdHashed);

            if (await _service.ProtestExists(model, hashedUserId))
            {
                await _service.UpdateProtest(model, hashedUserId);

                return RedirectToAction("Index");
            }

            return NotFound();
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> New(NewProtestModel model)
        {
            if (ModelState.IsValid)
            {
                var secretForeignKey = HttpContext.Session.GetString(Constants.UserIdHashed);

                if (!await _service.ProtestExists(model, secretForeignKey))
                {
                    var result = await _service.CreateProtestAsync(model, secretForeignKey);

                    if (result > 0)
                    {
                        return RedirectToAction("Index");
                    }
                }

                ModelState.AddModelError("Form", _localizationService.Get("CreateProtestError", "Unable to create protest."));
            }

            return View();
        }
        
        [Authorize]
        [HttpPost("/protest/attendance")]
        public async Task<bool> Attendance(Guid protestId)
        {
            var secretForeignKey = HttpContext.Session.GetString(Constants.UserIdHashed);

            return await _protestAttendanceService.ToggleAttendance(protestId, secretForeignKey);
        }
    }
}

GlobalProtestCalendar/Views/Protests/Details.cshtml
@using GlobalProtestCalendar.Business.Services
@using GlobalProtestCalendar.Models.Protest
@using Microsoft.AspNetCore.Localization
@model ProtestDetailsViewModel
@inject LocalizedCountryList LocalizedCountryList
@inject CommonLocalizationService localizer

@{
    Layout = "_LayoutInner";
    ViewData["Title"] = "Protest - " + Model.ProtestName;
    var requestCultureFeature = Context.Features.Get<IRequestCultureFeature>();
    var requestCulture = requestCultureFeature.RequestCulture;
}

@section Head
{
    <link rel="stylesheet" href="~/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="~/css/protest.scss"/>
    <link rel="stylesheet" href="~/css/protest-details.scss"/>
}

@section Scripts
{
    <script src="~/js/protest-details.js"></script>
    <script>
        GPC.init(@(User.Identity.IsAuthenticated.ToString().ToLower()), '@(Model.Id.ToString())')
    </script>

    @if (User.Identity.IsAuthenticated)
    {
        <script src="~/js/tinymce/tinymce.min.js" referrerpolicy="origin"></script>
        <script>
            tinymce.init({
              selector: 'textarea',  // change this value according to your HTML
              plugins: 'emoticons paste',
              width: '100%',
              paste_data_images: false,
              paste_as_text: true,
              menubar: false,
              branding: false,
              toolbar: 'emoticons bold italic strikethrough',
              resize: 'both'
            });
            
            
        </script>
    }
}

<section id="hero" class="hero mb-3" title="@localizer.Get("Click to change image")" style="background-image: url('@(Model.CoverImageUrl)')"></section>

<div class="attend-buttons d-flex flex-md-row justify-content-md-end mb-3">
    @if (Model.IsOwner)
    {
        <button class="btn btn-primary" style="cursor: default;opacity: .5">@localizer.Get("Attending", "I am attending")</button>
    }
    else
    {
        <button id="attending" style="@(Model.IsAttending ? "" : "display: none")" class="btn btn-primary ajax-button">@localizer.Get("Attending", "I am attending")</button>
        <button id="attend" style="@(Model.IsAttending ? "display: none" : "")" class="btn btn-primary ajax-button">@localizer.Get("Attend")</button>
    }
</div>

<form class="text-center text-sm-left">
    <div class="form-row">
        <div class="form-group col-sm-4">
            <label asp-for="ProtestName"></label>
            <label class="form-control">@Model.ProtestName</label>
        </div>
        <div class="form-group col-sm-2">
            <label asp-for="StartDate"></label>
            <label class="form-control">@Model.StartDate.ToShortDateString()</label>
        </div>
        <div class="form-group col-sm-2 text-center">
            <label asp-for="ConfirmedAttendees"></label>
            <label class="form-control" id="attendeeCount">@Model.ConfirmedAttendees</label>
        </div>
        <div class="form-group col-sm-4">
            <label asp-for="Duration"></label>
            <label class="form-control">@Model.Duration</label>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-sm-4">
            <label asp-for="Country"></label>
            <label class="form-control">@LocalizedCountryList.GetCountryList(requestCulture)[Model.Country]</label>
        </div>
        <div class="form-group col-sm-4">
            <label asp-for="Location"></label>
            <label class="form-control">@Model.Location</label>
        </div>
        <div class="form-group col-sm-4">
            <label asp-for="LocationDetails"></label>
            <label class="form-control">@Model.LocationDetails</label>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Motivation"></label>
        <div class="clearfix"></div>
        @if (Model.Motivation.Contains(Motivation.Political))
        {
            <span class="badge badge-primary">Political</span>
        }
        @if (Model.Motivation.Contains(Motivation.Corruption))
        {
            <span class="badge badge-primary">Corruption</span>
        }
        @if (Model.Motivation.Contains(Motivation.Economic))
        {
            <span class="badge badge-primary">Economic</span>
        }
    </div>
    <div class="form-group">
        <label asp-for="ProtestDescription"></label>
        <label class="form-control">@Model.ProtestDescription</label>
    </div>

    <div class="form-group">
        <label asp-for="ExpectedOutcome"></label>
        <label class="form-control">@Model.ExpectedOutcome</label>
    </div>
</form>

<div class="container mt-5">
    <div class="d-flex justify-content-center row">
        <div class="col">

            @if (User.Identity.IsAuthenticated)
            {
                <form asp-controller="Comments" asp-action="Index" class="mb-3">
                    <div id="new-comments" class="bg-light p-2" data-parent="#myGroup">
                        <div class="d-flex flex-row align-items-start">
                            <img class="rounded-circle d-none d-md-inline mr-md-2" src="https://i.imgur.com/RpzrMR2.jpg" width="40">
                            <textarea class="form-control ml-1 shadow-none textarea"></textarea>
                        </div>
                        <div class="mt-2 text-right">
                            <label>@localizer.Get("KnownAs", "Known as")</label>
                            <input type="text" placeholder="@localizer.Get("ProtestNickname", "Your nickname")" />
                            <button class="btn btn-primary btn-sm shadow-none" type="button">@localizer.Get("PostComment", "Post Comment")</button>
                        </div>
                        <span>@localizer.Get("NickNameTip", "Your nickname is how you are known in this protest only. This cannot be changed after your first comment")</span>
                    </div>
                </form>
            }

            <div class="d-flex flex-column comment-section" id="myGroup">
                <div class="bg-white p-2">
                    <div class="d-flex flex-row user-info">
                        <img class="rounded-circle" src="https://i.imgur.com/RpzrMR2.jpg" width="40">
                        <div class="d-flex flex-column justify-content-start ml-2">
                            <span class="d-block font-weight-bold name">Marry Andrews</span><span class="date text-black-50">Jan 2020</span>
                        </div>
                    </div>
                    <div class="mt-2">
                        <p class="comment-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                    </div>
                </div>
                <div class="bg-white p-2">
                    <div class="d-flex flex-row fs-12">
                        <div class="like p-2 cursor">
                            <i class="fa fa-thumbs-o-up"></i><span class="ml-1">Like</span>
                        </div>
                        <div class="like p-2 cursor action-collapse" data-toggle="collapse" aria-expanded="true" aria-controls="collapse-1" href="#collapse-1">
                            <i class="fa fa-commenting-o"></i><span class="ml-1">Comment</span>
                        </div>
                        <div class="like p-2 cursor action-collapse" data-toggle="collapse" aria-expanded="true" aria-controls="collapse-2" href="#collapse-2">
                            <i class="fa fa-share"></i><span class="ml-1">Share</span>
                        </div>
                    </div>
                </div>
                <div id="collapse-1" class="bg-light p-2 collapse" data-parent="#myGroup">
                    <div class="d-flex flex-row align-items-start">
                        <img class="rounded-circle" src="https://i.imgur.com/RpzrMR2.jpg" width="40"><textarea class="form-control ml-1 shadow-none textarea"></textarea>
                    </div>
                    <div class="mt-2 text-right">
                        <button class="btn btn-primary btn-sm shadow-none" type="button">Post comment</button><button class="btn btn-outline-primary btn-sm ml-1 shadow-none" type="button">Cancel</button>
                    </div>
                </div>
                <div id="collapse-2" class="bg-light p-2 collapse" data-parent="#myGroup">
                    <div class="d-flex flex-row align-items-start">
                        <i class="fa fa-facebook border p-3 rounded mr-1"></i><i class="fa fa-twitter border p-3 rounded mr-1"></i><i class="fa fa-linkedin border p-3 rounded mr-1"></i><i class="fa fa-instagram border p-3 rounded mr-1"></i><i class="fa fa-dribbble border p-3 rounded mr-1"></i> <i class="fa fa-pinterest-p border p-3 rounded mr-1"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GlobalProtestCalendar/Views/Protests/Edit.cshtml
@using GlobalProtestCalendar.Business.Services
@using GlobalProtestCalendar.Models.Protest
@using Microsoft.AspNetCore.Localization
@model GlobalProtestCalendar.Models.Protest.NewProtestModel
@inject CommonLocalizationService localizer
@inject LocalizedCountryList LocalizedCountryList

@{
    Layout = "_LayoutInner";
    var requestCultureFeature = Context.Features.Get<IRequestCultureFeature>();
    var requestCulture = requestCultureFeature.RequestCulture;
}

<section id="hero" class="hero mb-5" title="@localizer.Get("Click to change image")" style="background-image: url('@(Model.CoverImageUrl)')"></section>

<form asp-controller="Protests" asp-action="Edit" enctype="multipart/form-data">

    <input type="hidden" asp-for="Id" />

    <partial name="Shared/_Edit" model="Model" />
    
    <button type="submit" class="btn btn-primary mt-3">Update</button>
</form>

@section Head
{
    <link rel="stylesheet" href="~/css/protest.scss"/>
    <link rel="stylesheet" href="~/css/edit-protest.scss"/>
}

@section Scripts
{
    <partial name="_validationscriptspartial"/>

    <script>
       function showImage(src,target) {
         var fr=new FileReader();
         // when image is loaded, set the src of the image where you want to display it
         fr.onload = function(e) { 
             target.style.backgroundImage = 'url(' + this.result + ')';
         };
         src.addEventListener("change",function() {
           // fill fr with image data    
           fr.readAsDataURL(src.files[0]);
         });
       }

       var src = document.getElementById("CoverImage");
       var target = document.getElementById("hero");
       showImage(src,target);
       
       $('#hero').on('click', function() {
          src.click();
       });
       
       $('.cover-image-upload').css('opacity', 0).css('height', '1px');
       
       $('form').on('click', 'input[type=checkbox]', function(e){
           
           var c = $(e.target);
           console.log(c.is(':checked'))
           
           if (!c.is(':checked')) {
               if (!$('input[type=checkbox]').is(':checked')) {
                   setTimeout(function() {
                        c.click();
                   }, 50);
               }
           }
       })
    </script>
}

GlobalProtestCalendar/Views/Protests/Index.cshtml
@using GlobalProtestCalendar.Business.Services
@using GlobalProtestCalendar.Models.Protest
@using Microsoft.AspNetCore.Localization
@using GlobalProtestCalendar.Business
@model IList<ProtestListItem>
@inject LocalizedCountryList LocalizedCountryList

@{
    Layout = "_LayoutInner";
    ViewData["Title"] = "Protest Listing";
    var requestCultureFeature = Context.Features.Get<IRequestCultureFeature>();
    var requestCulture = requestCultureFeature.RequestCulture;
}
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">Country</th>
        <th scope="col">Protest Name</th>
        <th scope="col">Start Date</th>
        <th scope="col">Expected Outcome</th>
        <th scope="col">Motivation</th>
        <th scope="col">Duration</th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var protest in Model)
    {
        <tr class="protest-row" onclick="window.location ='/protests/@(UrlExtensions.CreateProtestDetailSlug(protest.Name, protest.Id))';" title="@protest.Description">
            <th scope="row">@LocalizedCountryList.GetCountryList(requestCulture)[protest.Country]</th>
            <td>@protest.Name</td>
            <td>@protest.StartDate</td>
            <td title="@protest.ExpectedOutcome">@protest.ExpectedOutcome</td>
            <td>
                @if (protest.Motivation.HasFlag(Motivation.Political))
                {
                    <span class="badge badge-primary">Political</span>
                }
                @if (protest.Motivation.HasFlag(Motivation.Corruption))
                {
                    <span class="badge badge-primary">Corruption</span>
                }
                @if (protest.Motivation.HasFlag(Motivation.Economic))
                {
                    <span class="badge badge-primary">Economic</span>
                }
            </td>
            <td>@protest.Duration</td>
            <td>
                <a asp-action="Edit" asp-controller="Protests" asp-route-id="@protest.Id">Edit</a>
            </td>
        </tr>
    }
    </tbody>
</table>

GlobalProtestCalendar/Views/Protests/New.cshtml
@using GlobalProtestCalendar.Business.Services
@using GlobalProtestCalendar.Models.Protest
@using Microsoft.AspNetCore.Localization
@model GlobalProtestCalendar.Models.Protest.NewProtestModel
@inject CommonLocalizationService localizer
@inject LocalizedCountryList LocalizedCountryList

@{
    Layout = "_LayoutInner";
    var requestCultureFeature = Context.Features.Get<IRequestCultureFeature>();
    var requestCulture = requestCultureFeature.RequestCulture;
}

<section id="hero" class="hero mb-5" title="@localizer.Get("Click to change image")" style="background-image: url('@(Model.CoverImageUrl)')"></section>

<form asp-controller="Protests" asp-action="New" enctype="multipart/form-data">

    <partial name="Shared/_Edit" model="Model" />
    
    <button type="submit" class="btn btn-primary mt-3">Create</button>
</form>

@section Head
{
    <link rel="stylesheet" href="~/css/protest.scss"/>
    <link rel="stylesheet" href="~/css/edit-protest.scss"/>
}

@section Scripts
{
    <partial name="_validationscriptspartial"/>

    <script>
       function showImage(src,target) {
         var fr=new FileReader();
         // when image is loaded, set the src of the image where you want to display it
         fr.onload = function(e) { 
             target.style.backgroundImage = 'url(' + this.result + ')';
         };
         src.addEventListener("change",function() {
           // fill fr with image data    
           fr.readAsDataURL(src.files[0]);
         });
       }

       var src = document.getElementById("CoverImage");
       var target = document.getElementById("hero");
       showImage(src,target);
       
       $('#hero').on('click', function() {
          src.click();
       });
       
       $('.cover-image-upload').css('opacity', 0).css('height', '1px');
       
       $('form').on('click', 'input[type=checkbox]', function(e){
           
           var c = $(e.target);
           console.log(c.is(':checked'))
           
           if (!c.is(':checked')) {
               if (!$('input[type=checkbox]').is(':checked')) {
                   setTimeout(function() {
                        c.click();
                   }, 50);
               }
           }
       })
    </script>
}