GlobalProtestCalendar/ViewComponents/CultureSwitcherViewComponent.cs
using System.Linq;
using GlobalProtestCalendar.Models;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace GlobalProtestCalendar.ViewComponents
{
    public class CultureSwitcherViewComponent : ViewComponent
    {
        private readonly IOptions<RequestLocalizationOptions> localizationOptions;

        public CultureSwitcherViewComponent(IOptions<RequestLocalizationOptions> localizationOptions) =>
            this.localizationOptions = localizationOptions;

        public IViewComponentResult Invoke()
        {
            var cultureFeature = HttpContext.Features.Get<IRequestCultureFeature>();
            var model = new CultureSwitcherModel
            {
                SupportedCultures = localizationOptions.Value.SupportedUICultures.ToList(),
                CurrentUICulture = cultureFeature.RequestCulture.UICulture
            };
            // ReSharper disable once Mvc.ViewComponentViewNotResolved
            return View(model);
        }
    }
}

GlobalProtestCalendar/Views/Shared/_Layout.cshtml
@using GlobalProtestCalendar.Business.Services
@inject CommonLocalizationService localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - @localizer.Get("Global Protest Calendar")</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.scss"/>
    @RenderSection("Head", required: false)
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <partial name="_LoginPartial"/>


                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@localizer.Get("Home")</a>
                    </li>
                    <li class="nav-item">
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

@RenderBody()

<footer class="border-top footer text-muted">
    <div class="container">
        <div class="row flex-column align-items-center flex-md-row justify-content-md-between">

            <span>&copy; @DateTime.UtcNow.Year - @localizer.Get("Global Protest Calendar")</span>
            <a asp-area="" asp-controller="Home" asp-action="Privacy">@localizer.Get("Privacy Policy")</a>
            <a asp-area="SinglePages" asp-page="/Faq">@localizer.Get("FAQ")</a>
            <a asp-area="SinglePages" asp-page="/About">@localizer.Get("About")</a>
            <vc:culture-switcher/>
        </div>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

GlobalProtestCalendar/Views/Shared/_LayoutInner.cshtml
@{
    Layout = "/Views/Shared/_Layout.cshtml";
}

@section Head
{
    @RenderSection("Head", required: false)
}

<div class="container">
    <main role="main" class="pb-3 mt-3">
        @RenderBody()
    </main>
</div>

@section Scripts
{
    @RenderSection("Scripts", required: false)
}

GlobalProtestCalendar/Views/Shared/_LayoutWide.cshtml
@{
    Layout = "_Layout";
}

@section Head
{
    @RenderSection("Head", required: false)
}

<main role="main" class="pb-3">
    @RenderBody()
</main>

@section Scripts
{
    @RenderSection("Scripts", required: false)
}